version: "{branch} {build}"

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble -s

test_script:
  - gradlew.bat check