version: "{branch} {build}"

build:
  verbosity: detailed

before_build:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version -Xmx32m

build_script:
  - gradlew.bat assemble -s --debug -PnexusUsername="arekbee" -PnexusPassword=""

test_script:
  - gradlew.bat check --debug -PnexusUsername="arekbee" -PnexusPassword=""